version: "3.9"

volumes:
  pg_data:

services:
  postgres:
    container_name: guests_app_database
    image: postgres:17.1-alpine3.20
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 10s
      retries: 5