"""Initial DB.

Revision ID: 22731844b8f7
Revises: 
Create Date: 2025-04-11 12:29:48.829944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22731844b8f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('inviter', sa.String(length=128), nullable=False),
    sa.Column('place_to_visit', sa.String(length=128), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    # ### end Alembic commands ###
