"""Add user model.

Revision ID: 68bdc7d7f5b4
Revises: d9802db2292c
Create Date: 2025-04-13 21:31:42.828180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bdc7d7f5b4'
down_revision = 'd9802db2292c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('is_approver', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('company_names', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('guest_full_names', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('inviter_full_names', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('places_to_visit', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places_to_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('inviter_full_names', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('guest_full_names', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('company_names', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))

    op.drop_table('users')
    # ### end Alembic commands ###
