"""Initial.

Revision ID: f139d5e9b91c
Revises: 
Create Date: 2025-04-20 14:45:02.554440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f139d5e9b91c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_names',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_full_names',
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('patronymic', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inviter_full_names',
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('patronymic', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places_to_visit',
    sa.Column('place', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('is_approver', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pass_requests',
    sa.Column('guest_full_name_id', sa.Integer(), nullable=True),
    sa.Column('inviter_full_name_id', sa.Integer(), nullable=True),
    sa.Column('company_name_id', sa.Integer(), nullable=True),
    sa.Column('place_to_visit_id', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_name_id'], ['company_names.id'], ),
    sa.ForeignKeyConstraint(['guest_full_name_id'], ['guest_full_names.id'], ),
    sa.ForeignKeyConstraint(['inviter_full_name_id'], ['inviter_full_names.id'], ),
    sa.ForeignKeyConstraint(['place_to_visit_id'], ['places_to_visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_requests')
    op.drop_table('users')
    op.drop_table('places_to_visit')
    op.drop_table('inviter_full_names')
    op.drop_table('guest_full_names')
    op.drop_table('company_names')
    # ### end Alembic commands ###
